# Generated by Django 4.2.7 on 2023-11-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='baskets',
        ),
        migrations.AddField(
            model_name='basket',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='startpage.order'),
            preserve_default=False,
        ),
    ]
