# Generated by Django 4.2.7 on 2023-11-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0004_order_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='hause',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
